plugins:
  - 'mocha-no-only'
env:
  node: true
  mocha: true
extends:
  - 'eslint-config-airbnb-base'
rules:
  no-underscore-dangle:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  operator-linebreak:
    - off
  mocha-no-only/mocha-no-only:
    - error
  function-paren-newline:
    - off
  object-curly-newline:
    - off
overrides:
  - files:
      - src/**/*.test.js
      - src/**/*.itest.js
      - src/**/*.etest.js
    rules:
      import/no-extraneous-dependencies:
        - off
      max-len:
        - off
      camelcase:
        - off
  - files:
      - db/migrations/**/*.js
      - db/models/**/*.js
    rules:
      max-len:
        - off
